<?php
if ($_GET['action'] == 'update') {
    $user = \Model\User\Repository::getOne($_GET['id']);
} else {
    $user = new \Model\User([]);
}
?>


<form  method="post" action="front.php?controller=users&action=create" enctype="multipart/form-data">
    <h1>Add new user</h1>
    <div>
        <input type="text" name="login"  value="<?php echo $user->login ?>" placeholder="login" >
    </div>
    <div >
        <input type="password" name="password" value="<?php echo $user->password ?>" placeholder="password" >
    </div>
    <div >
        <input type="password" name="password_confirm" value="<?php echo $user->password ?>" placeholder="password_confirm" >
    </div>
    <div >
        <input type="mail" name="mail" value="<?php echo $user->mail ?>" placeholder="mail" >
    </div>
    <div >
        <input type="text" name="name" value="<?php echo $user->name ?>" placeholder="full_name" >
    </div>

    <?php if ($_GET['action'] != 'update'): ?>
        <button type="submit" class="btn btn-primary">Create new User</button>
    <?php else:?>
        <button type="submit" class="btn btn-primary">Update</button>
    <?php endif;?>

</form>