
<?php
            $cart =  \Model\Cart\Repository::getOne($_SESSION['cart_id']);
            ?>

<form  method="post" action="http://dev8.php.mukovoz.com/WebSite/site/front.php?controller=order&action=send" >
    <h1>Сompletion order</h1>
    <div>
        <input type="text" name="last_name"   placeholder="last name" >
    </div>
    <div >
        <input type="text" name="first_name"  placeholder="first name" >
    </div>
    <div >
        <input type="text" name="email"  placeholder="email" >
    </div>
    <div >
        <input type="text" name="phone"  placeholder="phone" >
    </div>
    <div>
        Shipping method
        <select name="shipping_method">
            <?php foreach(\Model\Order::getAvailableShippingMethod() as $key=>$value):?>
                <option value="<?php echo $key?>"><?php echo $value?></option>
            <?php endforeach;?>
        </select>
    </div>
    <div>
        Payment method
        <select name="payment_method">
            <?php foreach(\Model\Order::getAvailablePaymentMethod() as $key=>$value):?>
                <option value="<?php echo $key?>"><?php echo $value?></option>
            <?php endforeach;?>
        </select>
    </div>
    <div>
        <option>Order cost - <?php echo $cart->getTotal();?> Usd</option>
    </div>

    <button type="submit" >Сheckout</button>
</form>


